// Validates the public deployment inputs and renders assembly/Deployment.ts. No dependencies; no secrets.
// usage: node render-inputs.cjs <inputs.json> <Deployment.ts out> <canonical inputs out>
'use strict';
const fs = require('fs');
const crypto = require('crypto');

const ALPHABET = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
const fail = message => { console.error('invalid deployment inputs: ' + message); process.exit(1); };
const sha = b => crypto.createHash('sha256').update(b).digest();

function base58(text) {
  if (typeof text !== 'string' || !/^[1-9A-HJ-NP-Za-km-z]{1,64}$/.test(text)) fail('bad base58');
  let n = 0n; for (const c of text) n = n * 58n + BigInt(ALPHABET.indexOf(c));
  const bytes = []; while (n > 0n) { bytes.unshift(Number(n & 255n)); n >>= 8n; }
  for (const c of text) { if (c !== '1') break; bytes.unshift(0); }
  return Buffer.from(bytes);
}
function address(text, what) {
  const a = base58(text);
  if (a.length !== 25 || a[0] !== 0 || !sha(sha(a.subarray(0, 21))).subarray(0, 4).equals(a.subarray(21))) fail(what + ' is not a checksummed Koinos address');
  return a;
}

const inputs = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
const keys = ['schema', 'template', 'templateVersion', 'network', 'chainId', 'koinContract', 'treasury', 'owners', 'threshold'];
if (!inputs || typeof inputs !== 'object' || Object.keys(inputs).sort().join() !== [...keys].sort().join()) fail('unexpected or missing fields');
if (inputs.schema !== 1 || inputs.template !== 'koinos-multisig-treasury' || inputs.templateVersion !== '1.0.0') fail('template identity');
if (!['local', 'testnet', 'mainnet'].includes(inputs.network)) fail('network');
if (typeof inputs.chainId !== 'string' || !/^[A-Za-z0-9_-]+=*$/.test(inputs.chainId)) fail('chainId encoding');
const chain = Buffer.from(inputs.chainId, 'base64url');
if (chain.length !== 34 || chain[0] !== 0x12 || chain[1] !== 0x20 || chain.toString('base64url') !== inputs.chainId.replace(/=+$/, '')) fail('chainId must be a sha2-256 multihash');
const koin = address(inputs.koinContract, 'koinContract');
const treasury = address(inputs.treasury, 'treasury');
if (!Array.isArray(inputs.owners) || inputs.owners.length < 3 || inputs.owners.length > 15) fail('3-15 owners required');
const owners = inputs.owners.map((o, i) => address(o, 'owner ' + i));
for (let i = 0; i < owners.length; i++) {
  if (owners[i].equals(treasury)) fail('the treasury cannot be an owner');
  if (i > 0 && Buffer.compare(owners[i - 1], owners[i]) >= 0) fail('owners must be unique and in ascending byte order');
}
const n = owners.length, t = inputs.threshold;
if (!Number.isInteger(t) || t < 2 || t <= Math.floor(n / 2) || t >= n) fail('threshold must be a majority of at least 2 and below the owner count');

const bytes = b => `[${[...b].join(', ')}]`;
const ts = [
  '// GENERATED by scripts/render-inputs.cjs from the reviewed public deployment inputs. Do not edit.',
  `// network ${inputs.network}; treasury ${inputs.treasury}; KOIN ${inputs.koinContract}`,
  `// owners ${inputs.owners.join(' ')}`,
  `export const DEPLOYMENT_CHAIN_ID: StaticArray<u8> = ${bytes(chain)};`,
  `export const DEPLOYMENT_TREASURY: StaticArray<u8> = ${bytes(treasury)};`,
  `export const DEPLOYMENT_KOIN: StaticArray<u8> = ${bytes(koin)};`,
  `export const DEPLOYMENT_OWNER_COUNT: i32 = ${owners.length};`,
  `export const DEPLOYMENT_OWNERS: StaticArray<u8> = ${bytes(Buffer.concat(owners))};`,
  `export const DEPLOYMENT_THRESHOLD: u32 = ${t};`,
  ''
].join('\n');
fs.writeFileSync(process.argv[3], ts);
fs.writeFileSync(process.argv[4], JSON.stringify(Object.fromEntries(keys.map(k => [k, inputs[k]])), null, 2) + '\n');
